use std::{
    cell::RefCell,
    env,
    fmt::Write as _,
    fs,
    path::{Path, PathBuf},
    process::{self, Command},
    rc::Rc,
    sync::{
        atomic::{AtomicBool, Ordering},
        mpsc, Arc, Mutex,
    },
    thread,
    time::{Duration, Instant},
};

use anyhow::{anyhow, Context, Result};
use cpal::{
    traits::{DeviceTrait, HostTrait, StreamTrait},
    Sample,
};
use serde::Deserialize;
use winit::{
    event::{Event, WindowEvent},
    event_loop::{ControlFlow, EventLoop},
    window::{Fullscreen, Window, WindowBuilder},
};

const PROBE_VISIBLE_MS: u64 = 140;
const DISPLAY_TIMEOUT: Duration = Duration::from_secs(8);
const AUDIO_TIMEOUT: Duration = Duration::from_secs(3);
const FOUR_K_WIDTH: u32 = 3840;
const FOUR_K_HEIGHT: u32 = 2160;
const TARGET_AUDIO_SAMPLE_RATE: u32 = 48_000;
const TARGET_AUDIO_BLOCK_FRAMES: u32 = 256;

fn main() {
    let mut report = ProbeReport::new();

    report.environment = EnvironmentInfo::collect();
    report.sched_fifo = probe_rtkit_sched_fifo();
    report.audio = probe_audio();
    report.display = probe_display();
    report.evaluate_hard_failures();

    let notes = report.to_markdown();
    let notes_path = manifest_path("PROBE_NOTES.md");
    if let Err(err) = fs::write(&notes_path, notes) {
        eprintln!("failed to write {}: {err:#}", notes_path.display());
        process::exit(1);
    }

    if report.hard_failures.is_empty() {
        process::exit(0);
    }

    for failure in &report.hard_failures {
        eprintln!("hard capability failure: {failure}");
    }
    process::exit(1);
}

fn manifest_path(file: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join(file)
}

#[derive(Debug, Default)]
struct ProbeReport {
    environment: EnvironmentInfo,
    display: DisplayProbe,
    audio: AudioProbe,
    sched_fifo: SchedFifoProbe,
    hard_failures: Vec<String>,
}

impl ProbeReport {
    fn new() -> Self {
        Self::default()
    }

    fn evaluate_hard_failures(&mut self) {
        if !self.display.rgba16float_render_target {
            self.hard_failures.push(
                "Rgba16Float is not usable as a sampled render target for phosphor textures"
                    .to_string(),
            );
        }

        if self.environment.is_hyprland_wayland() {
            match self.display.hyprland_vsync_ok {
                Some(true) => {}
                Some(false) => self.hard_failures.push(
                    "Hyprland Wayland borderless fullscreen did not verify FIFO vsync presentation"
                        .to_string(),
                ),
                None => self.hard_failures.push(
                    "Hyprland Wayland borderless fullscreen vsync could not be measured"
                        .to_string(),
                ),
            }

            if self.display.hyprland_probe_client_fullscreen == Some(0) {
                self.hard_failures.push(
                    "Hyprland did not report the probe window as fullscreen while measuring borderless fullscreen"
                        .to_string(),
                );
            }
        }
    }

    fn to_markdown(&self) -> String {
        let mut out = String::new();
        writeln!(out, "# Capability Probe Notes").unwrap();
        writeln!(out).unwrap();
        writeln!(
            out,
            "Generated by `capability_probe` as a one-shot binary. It opens one borderless fullscreen window frame, runs one cpal output callback block, records measurements, and exits."
        )
        .unwrap();
        writeln!(out).unwrap();

        writeln!(out, "## Summary").unwrap();
        if self.hard_failures.is_empty() {
            writeln!(out, "- Hard required assumptions: PASS").unwrap();
        } else {
            writeln!(out, "- Hard required assumptions: FAIL").unwrap();
            for failure in &self.hard_failures {
                writeln!(out, "  - {failure}").unwrap();
            }
        }
        writeln!(
            out,
            "- Manual verification required: confirm the fullscreen probe window appeared briefly and terminated. This cannot be fully automated."
        )
        .unwrap();
        writeln!(out).unwrap();

        writeln!(out, "## Environment").unwrap();
        writeln!(
            out,
            "- Session: XDG_SESSION_TYPE={}, XDG_CURRENT_DESKTOP={}, WAYLAND_DISPLAY={}, DISPLAY={}",
            value_or_unknown(self.environment.xdg_session_type.as_deref()),
            value_or_unknown(self.environment.xdg_current_desktop.as_deref()),
            value_or_unknown(self.environment.wayland_display.as_deref()),
            value_or_unknown(self.environment.display.as_deref()),
        )
        .unwrap();
        writeln!(
            out,
            "- Hyprland detected: {}",
            yes_no(self.environment.is_hyprland_wayland())
        )
        .unwrap();
        writeln!(
            out,
            "- PipeWire socket detected: {} ({})",
            yes_no(self.environment.pipewire_socket_present),
            self.environment
                .pipewire_socket
                .as_deref()
                .unwrap_or("no XDG_RUNTIME_DIR/pipewire-0 socket")
        )
        .unwrap();
        writeln!(
            out,
            "- Pulse socket detected: {} ({})",
            yes_no(self.environment.pulse_socket_present),
            self.environment
                .pulse_socket
                .as_deref()
                .unwrap_or("no XDG_RUNTIME_DIR/pulse/native socket")
        )
        .unwrap();
        writeln!(out).unwrap();

        writeln!(out, "## Display And Timing").unwrap();
        if let Some(error) = &self.display.error {
            writeln!(out, "- Display probe error: {error}").unwrap();
        }
        writeln!(
            out,
            "- Monitor: {}",
            self.display.monitor_name.as_deref().unwrap_or("unknown")
        )
        .unwrap();
        writeln!(
            out,
            "- Physical resolution: {}",
            format_size(self.display.monitor_physical_size)
        )
        .unwrap();
        writeln!(
            out,
            "- Window inner physical size: {}",
            format_size(self.display.window_physical_size)
        )
        .unwrap();
        writeln!(
            out,
            "- HiDPI scale factor: {}",
            self.display
                .scale_factor
                .map(|v| format!("{v:.3}"))
                .unwrap_or_else(|| "unknown".to_string())
        )
        .unwrap();
        writeln!(
            out,
            "- Monitor refresh rate: {}",
            self.display
                .refresh_millihertz
                .map(format_refresh)
                .unwrap_or_else(|| "unknown".to_string())
        )
        .unwrap();
        writeln!(
            out,
            "- Hyprland focused/client monitor: {}",
            self.display
                .hyprland_monitor_name
                .as_deref()
                .unwrap_or("unknown")
        )
        .unwrap();
        writeln!(
            out,
            "- Hyprland monitor physical resolution: {}",
            format_size(self.display.hyprland_monitor_physical_size)
        )
        .unwrap();
        writeln!(
            out,
            "- Hyprland monitor refresh rate: {}",
            self.display
                .hyprland_monitor_refresh_hz
                .map(|v| format!("{v:.3} Hz"))
                .unwrap_or_else(|| "unknown".to_string())
        )
        .unwrap();
        writeln!(
            out,
            "- Hyprland monitor scale: {}",
            self.display
                .hyprland_monitor_scale
                .map(|v| format!("{v:.3}"))
                .unwrap_or_else(|| "unknown".to_string())
        )
        .unwrap();
        writeln!(
            out,
            "- Hyprland probe client found: {}",
            self.display
                .hyprland_probe_client_found
                .map(yes_no)
                .unwrap_or("unknown")
        )
        .unwrap();
        writeln!(
            out,
            "- Hyprland probe client size: {}",
            format_size(self.display.hyprland_probe_client_size)
        )
        .unwrap();
        writeln!(
            out,
            "- Hyprland probe client fullscreen state: {}",
            self.display
                .hyprland_probe_client_fullscreen
                .map(|v| v.to_string())
                .unwrap_or_else(|| "unknown".to_string())
        )
        .unwrap();
        writeln!(
            out,
            "- Hyprland probe client monitor id: {}",
            self.display
                .hyprland_probe_client_monitor
                .map(|v| v.to_string())
                .unwrap_or_else(|| "unknown".to_string())
        )
        .unwrap();
        if let (Some(winit_size), Some(hypr_size)) = (
            self.display.window_physical_size,
            self.display.hyprland_probe_client_size,
        ) {
            if winit_size != hypr_size {
                writeln!(
                    out,
                    "- Hyprland/winit geometry note: winit reported inner size {}, while Hyprland reported fullscreen client size {}; prefer compositor/client measurements when deciding native fullscreen render resolution.",
                    format_size(Some(winit_size)),
                    format_size(Some(hypr_size))
                )
                .unwrap();
            }
        }
        writeln!(
            out,
            "- Adapter: {}",
            self.display.adapter_info.as_deref().unwrap_or("unknown")
        )
        .unwrap();
        writeln!(
            out,
            "- Surface formats: {}",
            format_list(&self.display.surface_formats)
        )
        .unwrap();
        writeln!(
            out,
            "- Surface Rgba16Float presentability: {}",
            yes_no(self.display.rgba16float_surface)
        )
        .unwrap();
        writeln!(
            out,
            "- Surface Rgba8Unorm fallback presentability: {}",
            yes_no(self.display.rgba8unorm_surface)
        )
        .unwrap();
        writeln!(
            out,
            "- Selected swapchain format: {}",
            self.display
                .selected_surface_format
                .as_deref()
                .unwrap_or("unknown")
        )
        .unwrap();
        writeln!(
            out,
            "- Rgba16Float sampled render-target support: {}",
            yes_no(self.display.rgba16float_render_target)
        )
        .unwrap();
        writeln!(
            out,
            "- Present modes: {}",
            format_list(&self.display.present_modes)
        )
        .unwrap();
        writeln!(
            out,
            "- Selected present mode: {}",
            self.display
                .selected_present_mode
                .as_deref()
                .unwrap_or("unknown")
        )
        .unwrap();
        writeln!(
            out,
            "- Redraw wait before one presented frame: {}",
            self.display
                .redraw_wait_ms
                .map(|v| format!("{v:.3} ms"))
                .unwrap_or_else(|| "unknown".to_string())
        )
        .unwrap();
        writeln!(
            out,
            "- Hyprland borderless fullscreen vsync result: {}",
            match self.display.hyprland_vsync_ok {
                Some(true) => "PASS: Wayland/Hyprland detected, FIFO vsync present mode was available, and one borderless fullscreen frame presented successfully. Use the Hyprland client fullscreen/size fields above for the compositor geometry verdict.",
                Some(false) => "FAIL: Wayland/Hyprland detected, but FIFO vsync presentation was not verified.",
                None if self.environment.is_hyprland_wayland() => "UNKNOWN: Hyprland detected but the display probe did not complete.",
                None => "Not applicable: session is not Hyprland Wayland.",
            }
        )
        .unwrap();
        writeln!(
            out,
            "- Vsync/tearing caveat: FIFO support and successful presentation are machine-checkable; visible tearing still needs the manual window confirmation above."
        )
        .unwrap();
        writeln!(out).unwrap();

        writeln!(out, "## GPU 4K Blit Budget").unwrap();
        writeln!(
            out,
            "- 4K full-screen blit target: {}x{}",
            FOUR_K_WIDTH, FOUR_K_HEIGHT
        )
        .unwrap();
        writeln!(
            out,
            "- 4K full-screen blit format: {}",
            self.display.blit_format.as_deref().unwrap_or("unknown")
        )
        .unwrap();
        writeln!(
            out,
            "- GPU timestamp query used: {}",
            yes_no(self.display.gpu_timestamp_used)
        )
        .unwrap();
        writeln!(
            out,
            "- 4K full-screen blit GPU time: {}",
            self.display
                .blit_gpu_time_ms
                .map(|v| format!("{v:.4} ms"))
                .unwrap_or_else(|| "unavailable".to_string())
        )
        .unwrap();
        writeln!(
            out,
            "- 144Hz frame budget comparison: {}",
            self.display
                .blit_gpu_time_ms
                .map(|v| {
                    let pct = v / (1000.0 / 144.0) * 100.0;
                    format!("{pct:.2}% of a 6.944 ms frame")
                })
                .unwrap_or_else(|| "unavailable".to_string())
        )
        .unwrap();
        if let Some(note) = &self.display.blit_note {
            writeln!(out, "- Blit note: {note}").unwrap();
        }
        writeln!(out).unwrap();

        writeln!(out, "## Audio Realtime Contract").unwrap();
        if let Some(error) = &self.audio.error {
            writeln!(out, "- Audio probe error: {error}").unwrap();
        }
        writeln!(
            out,
            "- Available cpal hosts: {}",
            format_list(&self.audio.available_hosts)
        )
        .unwrap();
        writeln!(
            out,
            "- Selected cpal host/backend: {}",
            self.audio.selected_host.as_deref().unwrap_or("unknown")
        )
        .unwrap();
        writeln!(
            out,
            "- PipeWire vs ALSA answer: {}",
            self.audio.pipewire_vs_alsa_answer()
        )
        .unwrap();
        writeln!(
            out,
            "- Default output device: {}",
            self.audio.device_name.as_deref().unwrap_or("unknown")
        )
        .unwrap();
        writeln!(
            out,
            "- Default output device id: {}",
            self.audio.device_id.as_deref().unwrap_or("unknown")
        )
        .unwrap();
        writeln!(
            out,
            "- Default output config: {}",
            self.audio.default_config.as_deref().unwrap_or("unknown")
        )
        .unwrap();
        writeln!(
            out,
            "- Requested output config: {}",
            self.audio.requested_config.as_deref().unwrap_or("unknown")
        )
        .unwrap();
        writeln!(
            out,
            "- Opened output config: {}",
            self.audio.opened_config.as_deref().unwrap_or("unknown")
        )
        .unwrap();
        writeln!(
            out,
            "- Actual callback block size: {}",
            self.audio
                .actual_block_frames
                .map(|v| format!("{v} frames"))
                .unwrap_or_else(|| "unknown".to_string())
        )
        .unwrap();
        writeln!(
            out,
            "- Actual sample rate: {}",
            self.audio
                .actual_sample_rate
                .map(|v| format!("{v} Hz"))
                .unwrap_or_else(|| "unknown".to_string())
        )
        .unwrap();
        writeln!(
            out,
            "- Target 256 samples at 48kHz met exactly: {}",
            yes_no(
                self.audio.actual_block_frames == Some(TARGET_AUDIO_BLOCK_FRAMES)
                    && self.audio.actual_sample_rate == Some(TARGET_AUDIO_SAMPLE_RATE)
            )
        )
        .unwrap();
        if !self.audio.stream_errors.is_empty() {
            writeln!(
                out,
                "- cpal stream errors during first block: {}",
                self.audio.stream_errors.join("; ")
            )
            .unwrap();
        }
        writeln!(out).unwrap();

        writeln!(out, "## SCHED_FIFO Via rtkit").unwrap();
        writeln!(
            out,
            "- rtkit DBus result: {}",
            if self.sched_fifo.success {
                "PASS"
            } else {
                "DEGRADED"
            }
        )
        .unwrap();
        writeln!(
            out,
            "- Attempted thread id: {}",
            self.sched_fifo
                .thread_id
                .map(|v| v.to_string())
                .unwrap_or_else(|| "unknown".to_string())
        )
        .unwrap();
        writeln!(
            out,
            "- Detail: {}",
            self.sched_fifo
                .detail
                .as_deref()
                .unwrap_or("no detail recorded")
        )
        .unwrap();
        writeln!(
            out,
            "- Design impact: rtkit failure is acceptable degradation per DESIGN.md; log and continue in the main crate."
        )
        .unwrap();
        writeln!(out).unwrap();

        writeln!(out, "## Phase Notes").unwrap();
        writeln!(
            out,
            "- Keep the main renderer using offscreen `Rgba16Float` phosphor textures only if the sampled render-target check above passes; the window surface can present through the selected 8-bit swapchain format if needed."
        )
        .unwrap();
        writeln!(
            out,
            "- Treat the measured 4K blit time as the baseline cost for each full-screen post-processing pass when budgeting for 144Hz."
        )
        .unwrap();
        writeln!(
            out,
            "- Use the recorded cpal backend, block size, and sample rate as the real audio contract instead of assuming PipeWire or a fixed 256-frame callback."
        )
        .unwrap();
        writeln!(
            out,
            "- Use the Hyprland result above to decide whether the next project task can stay on Wayland borderless fullscreen or should prefer an X11 session."
        )
        .unwrap();

        out
    }
}

#[derive(Debug, Default)]
struct EnvironmentInfo {
    xdg_session_type: Option<String>,
    xdg_current_desktop: Option<String>,
    wayland_display: Option<String>,
    display: Option<String>,
    hyprland_instance_signature: Option<String>,
    pipewire_socket_present: bool,
    pipewire_socket: Option<String>,
    pulse_socket_present: bool,
    pulse_socket: Option<String>,
}

impl EnvironmentInfo {
    fn collect() -> Self {
        let runtime_dir = env::var("XDG_RUNTIME_DIR").ok();
        let pipewire_socket = runtime_dir
            .as_deref()
            .map(|dir| Path::new(dir).join("pipewire-0"));
        let pulse_socket = runtime_dir
            .as_deref()
            .map(|dir| Path::new(dir).join("pulse/native"));

        Self {
            xdg_session_type: env::var("XDG_SESSION_TYPE").ok(),
            xdg_current_desktop: env::var("XDG_CURRENT_DESKTOP").ok(),
            wayland_display: env::var("WAYLAND_DISPLAY").ok(),
            display: env::var("DISPLAY").ok(),
            hyprland_instance_signature: env::var("HYPRLAND_INSTANCE_SIGNATURE").ok(),
            pipewire_socket_present: pipewire_socket.as_deref().is_some_and(Path::exists),
            pipewire_socket: pipewire_socket.map(|p| p.display().to_string()),
            pulse_socket_present: pulse_socket.as_deref().is_some_and(Path::exists),
            pulse_socket: pulse_socket.map(|p| p.display().to_string()),
        }
    }

    fn is_hyprland_wayland(&self) -> bool {
        let desktop_is_hyprland = self
            .xdg_current_desktop
            .as_deref()
            .is_some_and(|value| value.to_ascii_lowercase().contains("hyprland"));
        let session_is_wayland = self
            .xdg_session_type
            .as_deref()
            .is_some_and(|value| value.eq_ignore_ascii_case("wayland"));
        (desktop_is_hyprland || self.hyprland_instance_signature.is_some()) && session_is_wayland
    }
}

#[derive(Debug, Default)]
struct DisplayProbe {
    error: Option<String>,
    monitor_name: Option<String>,
    monitor_physical_size: Option<(u32, u32)>,
    window_physical_size: Option<(u32, u32)>,
    scale_factor: Option<f64>,
    refresh_millihertz: Option<u32>,
    hyprland_monitor_name: Option<String>,
    hyprland_monitor_physical_size: Option<(u32, u32)>,
    hyprland_monitor_refresh_hz: Option<f64>,
    hyprland_monitor_scale: Option<f64>,
    hyprland_probe_client_found: Option<bool>,
    hyprland_probe_client_size: Option<(u32, u32)>,
    hyprland_probe_client_fullscreen: Option<i64>,
    hyprland_probe_client_monitor: Option<i64>,
    adapter_info: Option<String>,
    surface_formats: Vec<String>,
    present_modes: Vec<String>,
    selected_surface_format: Option<String>,
    selected_present_mode: Option<String>,
    rgba16float_surface: bool,
    rgba8unorm_surface: bool,
    rgba16float_render_target: bool,
    redraw_wait_ms: Option<f64>,
    hyprland_vsync_ok: Option<bool>,
    blit_format: Option<String>,
    gpu_timestamp_used: bool,
    blit_gpu_time_ms: Option<f64>,
    blit_note: Option<String>,
}

fn probe_display() -> DisplayProbe {
    match probe_display_inner() {
        Ok(probe) => probe,
        Err(err) => DisplayProbe {
            error: Some(format!("{err:#}")),
            ..DisplayProbe::default()
        },
    }
}

fn probe_display_inner() -> Result<DisplayProbe> {
    let event_loop = EventLoop::new().context("create winit event loop")?;
    let probe = DisplayProbe::default();

    let window = WindowBuilder::new()
        .with_title("Asteroids capability probe")
        .with_fullscreen(Some(Fullscreen::Borderless(None)))
        .with_visible(true)
        .build(&event_loop)
        .context("create borderless fullscreen probe window")?;
    window.set_cursor_visible(false);

    let window: &'static Window = Box::leak(Box::new(window));
    let init_start = Instant::now();
    let mut gpu = pollster::block_on(GpuProbeState::new(window, probe))
        .context("initialize wgpu probe state")?;

    let result_cell = Rc::new(RefCell::new(None::<DisplayProbe>));
    let result_for_loop = Rc::clone(&result_cell);
    let deadline = Instant::now() + DISPLAY_TIMEOUT;
    let mut redraw_requested = false;

    event_loop
        .run(move |event, target| {
            target.set_control_flow(ControlFlow::WaitUntil(deadline));

            if Instant::now() >= deadline {
                let mut timed_out = gpu.finish_without_frame();
                timed_out.error =
                    Some("timed out waiting for one RedrawRequested event".to_string());
                *result_for_loop.borrow_mut() = Some(timed_out);
                target.exit();
                return;
            }

            match event {
                Event::WindowEvent { window_id, event } if window_id == window.id() => {
                    match event {
                        WindowEvent::RedrawRequested => {
                            let redraw_wait_ms = init_start.elapsed().as_secs_f64() * 1000.0;
                            window.pre_present_notify();
                            let frame_result = match gpu.render_one_frame(redraw_wait_ms) {
                                Ok(result) => result,
                                Err(err) => {
                                    let mut result = gpu.finish_without_frame();
                                    result.error = Some(format!("{err:#}"));
                                    result
                                }
                            };

                            if frame_result.error.is_none() {
                                thread::sleep(Duration::from_millis(PROBE_VISIBLE_MS));
                            }

                            *result_for_loop.borrow_mut() = Some(frame_result);
                            target.exit();
                        }
                        WindowEvent::CloseRequested => {
                            let mut closed = gpu.finish_without_frame();
                            closed.error = Some(
                                "probe window was closed before measurement completed".to_string(),
                            );
                            *result_for_loop.borrow_mut() = Some(closed);
                            target.exit();
                        }
                        _ => {}
                    }
                }
                Event::AboutToWait if !redraw_requested => {
                    redraw_requested = true;
                    window.request_redraw();
                }
                _ => {}
            }
        })
        .context("run one-shot winit event loop")?;

    let result = result_cell
        .borrow_mut()
        .take()
        .ok_or_else(|| anyhow!("display event loop exited without a result"));
    result
}

struct GpuProbeState {
    window: &'static Window,
    surface: wgpu::Surface<'static>,
    device: wgpu::Device,
    queue: wgpu::Queue,
    report: DisplayProbe,
    surface_config: wgpu::SurfaceConfiguration,
    timestamp_supported: bool,
}

impl GpuProbeState {
    async fn new(window: &'static Window, mut report: DisplayProbe) -> Result<Self> {
        let instance = wgpu::Instance::new(wgpu::InstanceDescriptor {
            backends: wgpu::Backends::all(),
            ..Default::default()
        });
        let surface = instance
            .create_surface(window)
            .context("create wgpu surface from window")?;
        let adapter = instance
            .request_adapter(&wgpu::RequestAdapterOptions {
                power_preference: wgpu::PowerPreference::HighPerformance,
                force_fallback_adapter: false,
                compatible_surface: Some(&surface),
            })
            .await
            .ok_or_else(|| anyhow!("no wgpu adapter compatible with the probe surface"))?;

        let adapter_info = adapter.get_info();
        report.adapter_info = Some(format!(
            "{} ({:?}, {:?}, driver: {})",
            adapter_info.name, adapter_info.backend, adapter_info.device_type, adapter_info.driver
        ));

        let caps = surface.get_capabilities(&adapter);
        report.surface_formats = caps
            .formats
            .iter()
            .map(|format| format!("{format:?}"))
            .collect();
        report.present_modes = caps
            .present_modes
            .iter()
            .map(|mode| format!("{mode:?}"))
            .collect();
        report.rgba16float_surface = caps.formats.contains(&wgpu::TextureFormat::Rgba16Float);
        report.rgba8unorm_surface = caps.formats.contains(&wgpu::TextureFormat::Rgba8Unorm);

        let surface_format = choose_surface_format(&caps.formats)
            .ok_or_else(|| anyhow!("surface reported no usable formats"))?;
        report.selected_surface_format = Some(format!("{surface_format:?}"));

        let present_mode = if caps.present_modes.contains(&wgpu::PresentMode::Fifo) {
            wgpu::PresentMode::Fifo
        } else {
            wgpu::PresentMode::AutoVsync
        };
        report.selected_present_mode = Some(format!("{present_mode:?}"));

        let adapter_features = adapter.features();
        let mut requested_features = wgpu::Features::empty();
        let timestamp_supported = adapter_features.contains(wgpu::Features::TIMESTAMP_QUERY);
        if timestamp_supported {
            requested_features |= wgpu::Features::TIMESTAMP_QUERY;
        }

        let (device, queue) = adapter
            .request_device(
                &wgpu::DeviceDescriptor {
                    label: Some("capability_probe_device"),
                    required_features: requested_features,
                    required_limits: wgpu::Limits::default(),
                },
                None,
            )
            .await
            .context("request wgpu device")?;

        let rgba16_features = adapter.get_texture_format_features(wgpu::TextureFormat::Rgba16Float);
        report.rgba16float_render_target = rgba16_features.allowed_usages.contains(
            wgpu::TextureUsages::RENDER_ATTACHMENT | wgpu::TextureUsages::TEXTURE_BINDING,
        );

        let size = window.inner_size();
        report.window_physical_size = Some((size.width, size.height));
        report.scale_factor = Some(window.scale_factor());

        let surface_config = wgpu::SurfaceConfiguration {
            usage: wgpu::TextureUsages::RENDER_ATTACHMENT,
            format: surface_format,
            width: size.width.max(1),
            height: size.height.max(1),
            present_mode,
            desired_maximum_frame_latency: 1,
            alpha_mode: caps
                .alpha_modes
                .iter()
                .copied()
                .find(|mode| *mode == wgpu::CompositeAlphaMode::Opaque)
                .unwrap_or(wgpu::CompositeAlphaMode::Auto),
            view_formats: vec![],
        };
        surface.configure(&device, &surface_config);

        Ok(Self {
            window,
            surface,
            device,
            queue,
            report,
            surface_config,
            timestamp_supported,
        })
    }

    fn render_one_frame(&mut self, redraw_wait_ms: f64) -> Result<DisplayProbe> {
        self.report.redraw_wait_ms = Some(redraw_wait_ms);
        self.refresh_window_measurements();

        let blit = measure_4k_blit(&self.device, &self.queue, self.timestamp_supported)
            .context("measure 4K fullscreen blit")?;
        self.report.blit_format = Some(format!("{:?}", blit.format));
        self.report.gpu_timestamp_used = blit.timestamp_used;
        self.report.blit_gpu_time_ms = blit.gpu_time_ms;
        self.report.blit_note = blit.note;

        let frame = self
            .surface
            .get_current_texture()
            .context("acquire surface texture for one frame")?;
        let view = frame
            .texture
            .create_view(&wgpu::TextureViewDescriptor::default());
        let mut encoder = self
            .device
            .create_command_encoder(&wgpu::CommandEncoderDescriptor {
                label: Some("probe_present_encoder"),
            });
        {
            let _pass = encoder.begin_render_pass(&wgpu::RenderPassDescriptor {
                label: Some("probe_visible_frame"),
                color_attachments: &[Some(wgpu::RenderPassColorAttachment {
                    view: &view,
                    resolve_target: None,
                    ops: wgpu::Operations {
                        load: wgpu::LoadOp::Clear(wgpu::Color {
                            r: 0.02,
                            g: 0.04,
                            b: 0.08,
                            a: 1.0,
                        }),
                        store: wgpu::StoreOp::Store,
                    },
                })],
                depth_stencil_attachment: None,
                timestamp_writes: None,
                occlusion_query_set: None,
            });
        }
        self.queue.submit(Some(encoder.finish()));
        frame.present();
        self.device.poll(wgpu::Maintain::Wait);
        self.refresh_hyprland_measurements();

        let fifo_selected = self.surface_config.present_mode == wgpu::PresentMode::Fifo;
        self.report.hyprland_vsync_ok = Some(fifo_selected);

        Ok(std::mem::take(&mut self.report))
    }

    fn refresh_window_measurements(&mut self) {
        if let Some(monitor) = self.window.current_monitor() {
            self.report.monitor_name = monitor.name();
            let monitor_size = monitor.size();
            self.report.monitor_physical_size = Some((monitor_size.width, monitor_size.height));
            self.report.refresh_millihertz = monitor.refresh_rate_millihertz();
        }

        let size = self.window.inner_size();
        self.report.window_physical_size = Some((size.width, size.height));
        self.report.scale_factor = Some(self.window.scale_factor());

        let width = size.width.max(1);
        let height = size.height.max(1);
        if self.surface_config.width != width || self.surface_config.height != height {
            self.surface_config.width = width;
            self.surface_config.height = height;
            self.surface.configure(&self.device, &self.surface_config);
        }
    }

    fn refresh_hyprland_measurements(&mut self) {
        if let Some(snapshot) = query_hyprland_snapshot(Some(process::id())) {
            if let Some(monitor) = snapshot.monitor {
                let refresh_millihertz = (monitor.refresh_rate * 1000.0).round() as u32;
                self.report
                    .monitor_name
                    .get_or_insert_with(|| monitor.name.clone());
                self.report
                    .monitor_physical_size
                    .get_or_insert((monitor.width, monitor.height));
                self.report
                    .refresh_millihertz
                    .get_or_insert(refresh_millihertz);

                self.report.hyprland_monitor_name = Some(monitor.name);
                self.report.hyprland_monitor_physical_size = Some((monitor.width, monitor.height));
                self.report.hyprland_monitor_refresh_hz = Some(monitor.refresh_rate);
                self.report.hyprland_monitor_scale = Some(monitor.scale);
            }
            self.report.hyprland_probe_client_found = Some(snapshot.client.is_some());
            if let Some(client) = snapshot.client {
                self.report.hyprland_probe_client_size =
                    Some((client.size[0].max(0) as u32, client.size[1].max(0) as u32));
                self.report.hyprland_probe_client_fullscreen = Some(client.fullscreen);
                self.report.hyprland_probe_client_monitor = Some(client.monitor);
            }
        }
    }

    fn finish_without_frame(&mut self) -> DisplayProbe {
        std::mem::take(&mut self.report)
    }
}

#[derive(Debug)]
struct HyprlandSnapshot {
    monitor: Option<HyprlandMonitor>,
    client: Option<HyprlandClient>,
}

#[derive(Clone, Debug, Deserialize)]
struct HyprlandMonitor {
    id: i64,
    name: String,
    width: u32,
    height: u32,
    #[serde(rename = "refreshRate")]
    refresh_rate: f64,
    scale: f64,
    focused: bool,
}

#[derive(Clone, Debug, Deserialize)]
struct HyprlandClient {
    size: [i32; 2],
    monitor: i64,
    fullscreen: i64,
    pid: i64,
}

fn query_hyprland_snapshot(pid: Option<u32>) -> Option<HyprlandSnapshot> {
    let monitors_output = Command::new("hyprctl")
        .args(["monitors", "-j"])
        .output()
        .ok()?;
    if !monitors_output.status.success() {
        return None;
    }
    let monitors: Vec<HyprlandMonitor> = serde_json::from_slice(&monitors_output.stdout).ok()?;

    let client = pid.and_then(|wanted_pid| {
        let output = Command::new("hyprctl")
            .args(["clients", "-j"])
            .output()
            .ok()?;
        if !output.status.success() {
            return None;
        }
        let clients: Vec<HyprlandClient> = serde_json::from_slice(&output.stdout).ok()?;
        clients
            .into_iter()
            .find(|client| client.pid == wanted_pid as i64)
    });

    let monitor = client
        .as_ref()
        .and_then(|client| {
            monitors
                .iter()
                .find(|monitor| monitor.id == client.monitor)
                .cloned()
        })
        .or_else(|| monitors.iter().find(|monitor| monitor.focused).cloned())
        .or_else(|| monitors.into_iter().next());

    Some(HyprlandSnapshot { monitor, client })
}

fn choose_surface_format(formats: &[wgpu::TextureFormat]) -> Option<wgpu::TextureFormat> {
    [
        wgpu::TextureFormat::Rgba16Float,
        wgpu::TextureFormat::Rgba8Unorm,
        wgpu::TextureFormat::Bgra8Unorm,
        wgpu::TextureFormat::Rgba8UnormSrgb,
        wgpu::TextureFormat::Bgra8UnormSrgb,
    ]
    .into_iter()
    .find(|format| formats.contains(format))
    .or_else(|| formats.first().copied())
}

struct BlitMeasurement {
    format: wgpu::TextureFormat,
    timestamp_used: bool,
    gpu_time_ms: Option<f64>,
    note: Option<String>,
}

fn measure_4k_blit(
    device: &wgpu::Device,
    queue: &wgpu::Queue,
    timestamp_supported: bool,
) -> Result<BlitMeasurement> {
    let format = wgpu::TextureFormat::Rgba16Float;
    let texture_size = wgpu::Extent3d {
        width: FOUR_K_WIDTH,
        height: FOUR_K_HEIGHT,
        depth_or_array_layers: 1,
    };

    let source = device.create_texture(&wgpu::TextureDescriptor {
        label: Some("probe_4k_blit_source"),
        size: texture_size,
        mip_level_count: 1,
        sample_count: 1,
        dimension: wgpu::TextureDimension::D2,
        format,
        usage: wgpu::TextureUsages::RENDER_ATTACHMENT | wgpu::TextureUsages::TEXTURE_BINDING,
        view_formats: &[],
    });
    let target = device.create_texture(&wgpu::TextureDescriptor {
        label: Some("probe_4k_blit_target"),
        size: texture_size,
        mip_level_count: 1,
        sample_count: 1,
        dimension: wgpu::TextureDimension::D2,
        format,
        usage: wgpu::TextureUsages::RENDER_ATTACHMENT | wgpu::TextureUsages::COPY_SRC,
        view_formats: &[],
    });
    let source_view = source.create_view(&wgpu::TextureViewDescriptor::default());
    let target_view = target.create_view(&wgpu::TextureViewDescriptor::default());

    let shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {
        label: Some("probe_4k_blit_shader"),
        source: wgpu::ShaderSource::Wgsl(
            r#"
struct VsOut {
    @builtin(position) pos: vec4<f32>,
    @location(0) uv: vec2<f32>,
};

@vertex
fn vs_main(@builtin(vertex_index) vertex_index: u32) -> VsOut {
    var positions = array<vec2<f32>, 3>(
        vec2<f32>(-1.0, -3.0),
        vec2<f32>(-1.0,  1.0),
        vec2<f32>( 3.0,  1.0),
    );
    var out: VsOut;
    let pos = positions[vertex_index];
    out.pos = vec4<f32>(pos, 0.0, 1.0);
    out.uv = pos * vec2<f32>(0.5, -0.5) + vec2<f32>(0.5, 0.5);
    return out;
}

@group(0) @binding(0) var src_tex: texture_2d<f32>;
@group(0) @binding(1) var src_sampler: sampler;

@fragment
fn fs_main(in: VsOut) -> @location(0) vec4<f32> {
    return textureSample(src_tex, src_sampler, in.uv);
}
"#
            .into(),
        ),
    });

    let bind_group_layout = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
        label: Some("probe_4k_blit_bind_group_layout"),
        entries: &[
            wgpu::BindGroupLayoutEntry {
                binding: 0,
                visibility: wgpu::ShaderStages::FRAGMENT,
                ty: wgpu::BindingType::Texture {
                    sample_type: wgpu::TextureSampleType::Float { filterable: false },
                    view_dimension: wgpu::TextureViewDimension::D2,
                    multisampled: false,
                },
                count: None,
            },
            wgpu::BindGroupLayoutEntry {
                binding: 1,
                visibility: wgpu::ShaderStages::FRAGMENT,
                ty: wgpu::BindingType::Sampler(wgpu::SamplerBindingType::NonFiltering),
                count: None,
            },
        ],
    });
    let sampler = device.create_sampler(&wgpu::SamplerDescriptor {
        label: Some("probe_4k_blit_sampler"),
        mag_filter: wgpu::FilterMode::Nearest,
        min_filter: wgpu::FilterMode::Nearest,
        ..Default::default()
    });
    let bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
        label: Some("probe_4k_blit_bind_group"),
        layout: &bind_group_layout,
        entries: &[
            wgpu::BindGroupEntry {
                binding: 0,
                resource: wgpu::BindingResource::TextureView(&source_view),
            },
            wgpu::BindGroupEntry {
                binding: 1,
                resource: wgpu::BindingResource::Sampler(&sampler),
            },
        ],
    });
    let pipeline_layout = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
        label: Some("probe_4k_blit_pipeline_layout"),
        bind_group_layouts: &[&bind_group_layout],
        push_constant_ranges: &[],
    });
    let pipeline = device.create_render_pipeline(&wgpu::RenderPipelineDescriptor {
        label: Some("probe_4k_blit_pipeline"),
        layout: Some(&pipeline_layout),
        vertex: wgpu::VertexState {
            module: &shader,
            entry_point: "vs_main",
            buffers: &[],
            compilation_options: Default::default(),
        },
        fragment: Some(wgpu::FragmentState {
            module: &shader,
            entry_point: "fs_main",
            targets: &[Some(wgpu::ColorTargetState {
                format,
                blend: None,
                write_mask: wgpu::ColorWrites::ALL,
            })],
            compilation_options: Default::default(),
        }),
        primitive: wgpu::PrimitiveState::default(),
        depth_stencil: None,
        multisample: wgpu::MultisampleState::default(),
        multiview: None,
    });

    let query_set = timestamp_supported.then(|| {
        device.create_query_set(&wgpu::QuerySetDescriptor {
            label: Some("probe_4k_blit_timestamps"),
            ty: wgpu::QueryType::Timestamp,
            count: 2,
        })
    });
    let query_buffer = timestamp_supported.then(|| {
        device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("probe_4k_blit_query_buffer"),
            size: 16,
            usage: wgpu::BufferUsages::QUERY_RESOLVE | wgpu::BufferUsages::COPY_SRC,
            mapped_at_creation: false,
        })
    });
    let readback_buffer = timestamp_supported.then(|| {
        device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("probe_4k_blit_query_readback"),
            size: 16,
            usage: wgpu::BufferUsages::COPY_DST | wgpu::BufferUsages::MAP_READ,
            mapped_at_creation: false,
        })
    });

    let mut encoder = device.create_command_encoder(&wgpu::CommandEncoderDescriptor {
        label: Some("probe_4k_blit_encoder"),
    });

    {
        let _clear = encoder.begin_render_pass(&wgpu::RenderPassDescriptor {
            label: Some("probe_4k_blit_source_clear"),
            color_attachments: &[Some(wgpu::RenderPassColorAttachment {
                view: &source_view,
                resolve_target: None,
                ops: wgpu::Operations {
                    load: wgpu::LoadOp::Clear(wgpu::Color {
                        r: 0.8,
                        g: 0.8,
                        b: 0.8,
                        a: 1.0,
                    }),
                    store: wgpu::StoreOp::Store,
                },
            })],
            depth_stencil_attachment: None,
            timestamp_writes: None,
            occlusion_query_set: None,
        });
    }

    let timestamp_writes = query_set
        .as_ref()
        .map(|set| wgpu::RenderPassTimestampWrites {
            query_set: set,
            beginning_of_pass_write_index: Some(0),
            end_of_pass_write_index: Some(1),
        });
    {
        let mut pass = encoder.begin_render_pass(&wgpu::RenderPassDescriptor {
            label: Some("probe_4k_fullscreen_blit"),
            color_attachments: &[Some(wgpu::RenderPassColorAttachment {
                view: &target_view,
                resolve_target: None,
                ops: wgpu::Operations {
                    load: wgpu::LoadOp::Clear(wgpu::Color::BLACK),
                    store: wgpu::StoreOp::Store,
                },
            })],
            depth_stencil_attachment: None,
            timestamp_writes,
            occlusion_query_set: None,
        });
        pass.set_pipeline(&pipeline);
        pass.set_bind_group(0, &bind_group, &[]);
        pass.draw(0..3, 0..1);
    }

    if let (Some(query_set), Some(query_buffer), Some(readback_buffer)) =
        (&query_set, &query_buffer, &readback_buffer)
    {
        encoder.resolve_query_set(query_set, 0..2, query_buffer, 0);
        encoder.copy_buffer_to_buffer(query_buffer, 0, readback_buffer, 0, 16);
    }

    let cpu_start = Instant::now();
    queue.submit(Some(encoder.finish()));
    device.poll(wgpu::Maintain::Wait);
    let cpu_elapsed_ms = cpu_start.elapsed().as_secs_f64() * 1000.0;

    if let Some(readback) = readback_buffer {
        let slice = readback.slice(..);
        let (tx, rx) = mpsc::channel();
        slice.map_async(wgpu::MapMode::Read, move |result| {
            let _ = tx.send(result);
        });
        device.poll(wgpu::Maintain::Wait);
        rx.recv_timeout(Duration::from_secs(2))
            .context("wait for timestamp readback mapping")?
            .context("map timestamp readback buffer")?;
        let data = slice.get_mapped_range();
        let timestamps: &[u64] = bytemuck::cast_slice(&data);
        let ticks = timestamps
            .get(1)
            .zip(timestamps.first())
            .map(|(end, start)| end.saturating_sub(*start))
            .unwrap_or(0);
        let period_ns = queue.get_timestamp_period() as f64;
        drop(data);
        readback.unmap();

        return Ok(BlitMeasurement {
            format,
            timestamp_used: true,
            gpu_time_ms: Some((ticks as f64 * period_ns) / 1_000_000.0),
            note: Some(format!(
                "Timestamp covered only the sampled full-screen render pass; CPU submit+wait for the encoded work was {cpu_elapsed_ms:.4} ms."
            )),
        });
    }

    Ok(BlitMeasurement {
        format,
        timestamp_used: false,
        gpu_time_ms: Some(cpu_elapsed_ms),
        note: Some(
            "Adapter did not expose TIMESTAMP_QUERY; value is CPU submit+wait time, not a strict GPU timestamp."
                .to_string(),
        ),
    })
}

#[derive(Debug, Default)]
struct AudioProbe {
    error: Option<String>,
    available_hosts: Vec<String>,
    selected_host: Option<String>,
    device_name: Option<String>,
    device_id: Option<String>,
    default_config: Option<String>,
    requested_config: Option<String>,
    opened_config: Option<String>,
    actual_block_frames: Option<u32>,
    actual_sample_rate: Option<u32>,
    stream_errors: Vec<String>,
}

impl AudioProbe {
    fn pipewire_vs_alsa_answer(&self) -> String {
        match self.selected_host.as_deref() {
            Some(host) if host.eq_ignore_ascii_case("ALSA") => {
                "cpal selected ALSA as the host/backend. PipeWire may still sit behind ALSA/Pulse on this desktop, but cpal is not using a native PipeWire host.".to_string()
            }
            Some(host) if host.to_ascii_lowercase().contains("pipewire") => {
                format!("cpal selected PipeWire directly ({host}).")
            }
            Some(host) => format!("cpal selected {host}; not ALSA or PipeWire."),
            None => "cpal host selection failed.".to_string(),
        }
    }
}

#[derive(Clone, Debug)]
struct AudioBlock {
    frames: u32,
}

fn probe_audio() -> AudioProbe {
    let mut probe = AudioProbe {
        available_hosts: cpal::available_hosts()
            .into_iter()
            .map(|host| host.name().to_string())
            .collect(),
        ..AudioProbe::default()
    };

    if let Err(err) = probe_audio_inner(&mut probe) {
        probe.error = Some(format!("{err:#}"));
    }

    probe
}

fn probe_audio_inner(probe: &mut AudioProbe) -> Result<()> {
    let host = cpal::default_host();
    probe.selected_host = Some(host.id().name().to_string());

    let device = host
        .default_output_device()
        .ok_or_else(|| anyhow!("no default cpal output device"))?;
    probe.device_name = device.description().ok().map(|description| {
        let mut name = description.name().to_string();
        if let Some(driver) = description.driver() {
            name.push_str(" [driver: ");
            name.push_str(driver);
            name.push(']');
        }
        name
    });
    probe.device_id = device.id().ok().map(|id| id.to_string());

    let default_config = device
        .default_output_config()
        .context("query default output config")?;
    probe.default_config = Some(format!("{default_config:?}"));

    let sample_format = default_config.sample_format();
    let mut preferred_config = default_config.config();
    preferred_config.sample_rate = TARGET_AUDIO_SAMPLE_RATE;
    preferred_config.buffer_size = cpal::BufferSize::Fixed(TARGET_AUDIO_BLOCK_FRAMES);
    probe.requested_config = Some(format!(
        "{:?}, sample_format={sample_format:?}",
        preferred_config
    ));

    let stream_errors = Arc::new(Mutex::new(Vec::<String>::new()));
    let first_block_seen = Arc::new(AtomicBool::new(false));
    let (tx, rx) = mpsc::channel::<AudioBlock>();

    let stream_result = build_audio_stream(
        &device,
        sample_format,
        preferred_config.clone(),
        Arc::clone(&stream_errors),
        Arc::clone(&first_block_seen),
        tx.clone(),
    );

    let (stream, opened_config, opened_note) = match stream_result {
        Ok(stream) => (stream, preferred_config, None),
        Err(preferred_err) => {
            let fallback_config = default_config.config();
            probe.requested_config = Some(format!(
                "{:?}, sample_format={sample_format:?}; preferred 48k/256 failed: {preferred_err}",
                fallback_config
            ));
            let stream = build_audio_stream(
                &device,
                sample_format,
                fallback_config.clone(),
                Arc::clone(&stream_errors),
                first_block_seen,
                tx,
            )
            .with_context(|| {
                format!(
                    "build output stream with preferred config failed ({preferred_err}); fallback default config also failed"
                )
            })?;
            (
                stream,
                fallback_config,
                Some(format!("preferred 48k/256 config failed: {preferred_err}")),
            )
        }
    };

    probe.opened_config = Some(format!(
        "{:?}, sample_format={sample_format:?}{}",
        opened_config,
        opened_note
            .as_deref()
            .map(|note| format!(" ({note})"))
            .unwrap_or_default()
    ));
    probe.actual_sample_rate = Some(opened_config.sample_rate);

    stream.play().context("start cpal output stream")?;
    let block = rx
        .recv_timeout(AUDIO_TIMEOUT)
        .context("wait for one cpal output callback block")?;
    probe.actual_block_frames = Some(block.frames);
    drop(stream);

    probe.stream_errors = stream_errors
        .lock()
        .map(|errors| errors.clone())
        .unwrap_or_else(|_| vec!["stream error mutex was poisoned".to_string()]);

    Ok(())
}

fn build_audio_stream(
    device: &cpal::Device,
    sample_format: cpal::SampleFormat,
    config: cpal::StreamConfig,
    stream_errors: Arc<Mutex<Vec<String>>>,
    first_block_seen: Arc<AtomicBool>,
    tx: mpsc::Sender<AudioBlock>,
) -> Result<cpal::Stream> {
    let channels = config.channels.max(1) as usize;
    let error_errors = Arc::clone(&stream_errors);
    let stream = device.build_output_stream_raw(
        &config,
        sample_format,
        move |data, _| {
            let frames = (data.len() / channels) as u32;
            fill_silence(data);
            if !first_block_seen.swap(true, Ordering::SeqCst) {
                let _ = tx.send(AudioBlock { frames });
            }
        },
        move |err| {
            if let Ok(mut errors) = error_errors.lock() {
                errors.push(err.to_string());
            }
        },
        Some(Duration::from_millis(500)),
    )?;
    Ok(stream)
}

fn fill_silence(data: &mut cpal::Data) {
    match data.sample_format() {
        cpal::SampleFormat::I8 => fill_typed(data, 0_i8),
        cpal::SampleFormat::I16 => fill_typed(data, 0_i16),
        cpal::SampleFormat::I24 => fill_typed(data, cpal::I24::from_sample(0.0_f32)),
        cpal::SampleFormat::I32 => fill_typed(data, 0_i32),
        cpal::SampleFormat::I64 => fill_typed(data, 0_i64),
        cpal::SampleFormat::U8 => fill_typed(data, u8::MAX / 2),
        cpal::SampleFormat::U16 => fill_typed(data, u16::MAX / 2),
        cpal::SampleFormat::U24 => fill_typed(data, cpal::U24::from_sample(0.0_f32)),
        cpal::SampleFormat::U32 => fill_typed(data, u32::MAX / 2),
        cpal::SampleFormat::U64 => fill_typed(data, u64::MAX / 2),
        cpal::SampleFormat::F32 => fill_typed(data, 0.0_f32),
        cpal::SampleFormat::F64 => fill_typed(data, 0.0_f64),
        cpal::SampleFormat::DsdU8 | cpal::SampleFormat::DsdU16 | cpal::SampleFormat::DsdU32 => {
            data.bytes_mut().fill(0x69)
        }
        _ => data.bytes_mut().fill(0),
    }
}

fn fill_typed<T>(data: &mut cpal::Data, value: T)
where
    T: cpal::SizedSample + Copy,
{
    if let Some(samples) = data.as_slice_mut::<T>() {
        samples.fill(value);
    } else {
        data.bytes_mut().fill(0);
    }
}

#[derive(Debug, Default)]
struct SchedFifoProbe {
    success: bool,
    thread_id: Option<u64>,
    detail: Option<String>,
}

fn probe_rtkit_sched_fifo() -> SchedFifoProbe {
    let thread_id = current_thread_id();
    match probe_rtkit_sched_fifo_inner(thread_id) {
        Ok(detail) => SchedFifoProbe {
            success: true,
            thread_id: Some(thread_id),
            detail: Some(detail),
        },
        Err(err) => SchedFifoProbe {
            success: false,
            thread_id: Some(thread_id),
            detail: Some(format!("{err:#}")),
        },
    }
}

fn probe_rtkit_sched_fifo_inner(thread_id: u64) -> Result<String> {
    let connection = zbus::blocking::Connection::system().context("connect to system DBus")?;
    let proxy = zbus::blocking::Proxy::new(
        &connection,
        "org.freedesktop.RealtimeKit1",
        "/org/freedesktop/RealtimeKit1",
        "org.freedesktop.RealtimeKit1",
    )
    .context("create rtkit proxy")?;

    let priority = 10_u32;
    proxy
        .call_method("MakeThreadRealtime", &(thread_id, priority))
        .with_context(|| {
            format!("call rtkit MakeThreadRealtime(thread={thread_id}, priority={priority})")
        })?;
    Ok(format!(
        "MakeThreadRealtime(thread={thread_id}, priority={priority}) succeeded"
    ))
}

fn current_thread_id() -> u64 {
    unsafe { libc::syscall(libc::SYS_gettid) as u64 }
}

fn value_or_unknown(value: Option<&str>) -> &str {
    value.unwrap_or("unknown")
}

fn yes_no(value: bool) -> &'static str {
    if value {
        "yes"
    } else {
        "no"
    }
}

fn format_size(size: Option<(u32, u32)>) -> String {
    size.map(|(width, height)| format!("{width}x{height}"))
        .unwrap_or_else(|| "unknown".to_string())
}

fn format_refresh(millihertz: u32) -> String {
    format!("{:.3} Hz", millihertz as f64 / 1000.0)
}

fn format_list(values: &[String]) -> String {
    if values.is_empty() {
        "none".to_string()
    } else {
        values.join(", ")
    }
}
